services:
  mariadb:
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build: 
      context: requirements/mariadb
    env_file: .env 
    restart: on-failure

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    networks:
      - inception
    build: 
      context: requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ethan/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ethan/data/mariadb

networks:
  inception:
    driver: bridge